### ISSUE TITLE
ESP8266

### ISSUE THREAD

**Issue by luetzel** [blueberrye-io/BB-EE893#1]
Howdy,
I'm struggling with this sensor on a ESP8266 µC. Do you have any code examples
ready for ESP8266? Here the problem seems to be the Wire.h. As far as I understand
`
TWBR = 200;  // set the TWBR register (bypass wire library) reduce the speed about 3 times
TWSR |= bit (TWPS0);
TWSR |= bit (TWPS1);
`
must be replaced with:
`
Wire.setClock(2000);
`
on ESP8266. However, I'm not sure about the speed and I cannot retrieve any data.

**Comment by gerhard-gs68** [comment]
Hallo,

actually I do not have at hand, but if you check the implementation it seems its corrected to 100kHz if you set lower values (esp8266/Arduino repository at github,  Arduino/cores/esp8266/core_esp8266_si2c.c)

void twi_setClock(unsigned int freq){
#if F_CPU == FCPU80
  if(freq <= 100000) twi_dcount = 19;//about 100KHz
  else if(freq <= 200000) twi_dcount = 8;//about 200KHz
  else if(freq <= 300000) twi_dcount = 3;//about 300KHz
  else if(freq <= 400000) twi_dcount = 1;//about 400KHz
  else twi_dcount = 1;//about 400KHz
#else
  if(freq <= 100000) twi_dcount = 32;//about 100KHz
  else if(freq <= 200000) twi_dcount = 14;//about 200KHz
  else if(freq <= 300000) twi_dcount = 8;//about 300KHz
  else if(freq <= 400000) twi_dcount = 5;//about 400KHz
  else if(freq <= 500000) twi_dcount = 3;//about 500KHz
  else if(freq <= 600000) twi_dcount = 2;//about 600KHz
  else twi_dcount = 1;//about 700KHz
#endif
}

maybe you can adapt the source code, or try to find another software I2C lib that allows you to set slower speed.

Best Regards
Gerhrad

**Comment by luetzel** [comment]
Hi Gerhard,
thanks for your fast reply. I tried to set the speed to
100K with
`twi_setClock(100000)`
however, I cannot retrieve any data.
I wonder if it could be related to the level-shifter that I hooked-up in between the sensor and ESP8266

**Comment by gerhard-gs68** [comment]
Hi,

100k is much to fast. If i recall correctly you need about 20k. Based on the code of the wire library cited before you cannot come down below 100k.

In addition you need the levelshifter (I assume based on the standard circuit with discrete transistors) with pull up resistors, the EE893 is a (almost) 5V device.

Best Regards
Gerhard

**Comment by luetzel** [comment]
ok, I tried to go below 20k using different values for twi_dcount
'
if(freq <if(freq <= 20000) twi_dcount = 40;
'
in core_esp8266_si2c.c, but it does not help.
Not sure if it is possible to go down below <20k

**Comment by gerhard-gs68** [comment]
HiCould you make sure that the wire library was recompiled? Ich guess for compiling a Sketch a existing library will be used.I checked github.com and found e.g. XantoI2C that seems to be pure arduino and goes down to 25kHz.Hope this help sichGerhard luetzel <notifications@github.com> hat am 1. August 2017 um 17:44 geschrieben:ok, I tried to go below 20k using different values for twi_dcount'if(freq <if(freq <= 20000) twi_dcount = 40;'in core_esp8266_si2c.c, but it does not help.Not sure if it is possible to go down below <20k--You are receiving this because you commented.Reply to this email directly or view it on GitHub:https://github.com/blueberrye-io/BB-EE893/issues/1#issuecomment-319410783

**Comment by luetzel** [comment]
Hi Gerhard,
thanks for your help and time. I'm giving up! I was a little reluctant buying this sensor, since there were no code examples around. Ok it works on Arduino, but it is useless for us, if it doesn't work on ESP8266. Unfortunately, I don't have time and enough coding skills to fix this problem. Cheers, /luetzel

**Comment by Graham5040** [comment]
Hi luetzel
I used SWire instead of Wire Library and have made an example at 
Graham5040/EE893-CO2-Sensor-on-ESP8266
Changed to Swire and use SWire.delay_time_us = 150; after SWire.begin().  Change references on "wire" to "SWire" a remove all the Atmel registers lines.

Tested on a ESP8266. Don't forget the level shifters are needed as EE893 is 5V.
Graham
